version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.8.1
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: 'please enter your fernet key here'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    command: >
          bash -c "airflow db init &&
           airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com" 
           #please change the password after the initial use for security purposes
    volumes:
      - ../../data:/opt/airflow/dags/data
      
  airflow-scheduler:
    image: apache/airflow:2.8.1
    restart: always
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: 'please enter your fernet key here'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    volumes:
      - ../../dags:/opt/airflow/dags
      - ../../logs:/opt/airflow/logs
      - ../../plugins:/opt/airflow/plugins
      - ../../data:/opt/airflow/data
    command: airflow scheduler

  airflow-webserver:
    image: apache/airflow:2.8.1
    restart: always
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: 'please enter your fernet key here'
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
    volumes:
      - ../../dags:/opt/airflow/dags
      - ../../logs:/opt/airflow/logs
      - ../../plugins:/opt/airflow/plugins
      - ../../data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: airflow webserver

volumes:
  postgres_data:
